apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-sentinel
spec:
  replicas: 1
  selector:
    redis-sentinel: "true"
  template:
    metadata:
      labels:
        name: redis-sentinel
        redis-sentinel: "true"
        role: sentinel
    spec:
      containers:
      - name: sentinel
        image: clamoriniere1a/redis-openshift
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
        volumeMounts:
          - mountPath: /redis-sentinel
            name: data
      volumes:
        - name: data
          emptyDir: {}
